language: perl
arch:
  - amd64
  - ppc64le
perl:
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "dev"
  - "blead"

matrix:
  fast_finish: true
  allow_failures:
    - perl: blead

before_install:
   - sudo apt-get update
   - sudo apt-get install devscripts dpkg-dev lsb-release
   - eval $(curl https://travis-perl.github.io/init)
   - build-perl
   - perl -V

install:
   - yes '' | cpanm --verbose --notest --skip-satisfied Data::Validate::Domain Data::Validate::IP Data::Validate::URI File::Slurp File::Which Log::Message Term::UI Test::NoTabs Test::Pod::Coverage Test::Pod Text::Template Devel::Cover::Report::Coveralls Sort::Versions
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 PATH=bin:${PERLBREW_PATH}:${PATH}

script:
   - make test-verbose

after_success:
   - prove --exec 'env PERL5OPT=-MDevel::Cover=-ignore_re,^(t/|/usr) perl' t/*.t
   - cover -ignore_re '^(t/|/usr)' -report coveralls

notifications:
  irc: "irc.lugs.ch#kivamon"
